eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
server:
  port: 9092
spring:
  application:
    name: service-hi

# Feign连接端点
buff:
  app:
    buff-base:
      url: http://localhost:9092
    buff-auth:
      url: http://localhost:8899